#!/bin/bash

set -eo pipefail

cd /opt/plextube/videos

while true; do
	xargs -n1 yt-dlp \
		--embed-thumbnail \
		--add-metadata \
		-f best \
		-cw \
		--yes-playlist \
		--dateafter now-2weeks \
		--break-on-reject \
		--embed-subs \
		--compat-options filename \
		--download-archive /opt/plextube/archive -- < /opt/plextube/subs.txt || true

	sleep 600
done
