name: CI

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: |
          docker build -t ghcr.io/bahlo/plextube:latest .
          docker push ghcr.io/bahlo/plextube:latest
